export default [
  'Amo las agujetas de mañana',
  'Aquí venimos a sudar, no a peinarnos',
  'Cuida tu cuerpo, es tu única casa',
  'Despierta. Entrena. Repite',
  'El cuerpo logra lo que la mente cree',
  'El día de pierna NO se salta',
  'El dolor no existe',
  'El hierro no engaña',
  'El mejor proyecto en el que trabajarás eres tú',
  'El sofá no te va a poner en forma',
  'Empieza donde estás, usa lo que tienes',
  'Energía que se crea, energía que se queda',
  'Entrena como una bestia',
  'Entrena para la vida, no solo para el espejo',
  'Haz que hoy cuente',
  'Hoy es tu día',
  'Invierte en ti, los resultados hablan',
  'La excusa quema cero calorías',
  'Levanta pesado hoy, agradécelo mañana',
  'Lo que pasa en el gym, se queda en el gym',
  'Sé más fuerte que tus excusas',
  'Menos charla, más acción',
  'Menos drama y más sentadillas',
  'Moverse es vivir',
  'No hay magia, solo hierro y sudor',
  'Prohibido rendirse (y prohibido no sudar)',
  'Rompe tus marcas',
  'Salud de hierro, mente de acero',
  'Si fuera fácil, lo haría cualquiera',
  'Si no te reta, no te cambia',
  'Sobreviviendo a un burpee a la vez',
  'Solo compites contigo mismo',
  'Sudar es progresar',
  'Tu cuerpo puede con casi todo, es a tu mente a quien debes convencer',
  'Tu sudor es tu grasa llorando',
  'Tu única competencia está en el espejo',
  'Un día más, un día mejor',
].sort(() => Math.random() < 0.5)
